# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: logging_service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'logging_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15logging_service.proto\x12\x07logging\"=\n\nLogMessage\x12\x0b\n\x03log\x18\x01 \x01(\t\x12\x0f\n\x07service\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\"\x1d\n\x0bLogResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2K\n\x0eLoggingService\x12\x39\n\nStreamLogs\x12\x13.logging.LogMessage\x1a\x14.logging.LogResponse(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'logging_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGMESSAGE']._serialized_start=34
  _globals['_LOGMESSAGE']._serialized_end=95
  _globals['_LOGRESPONSE']._serialized_start=97
  _globals['_LOGRESPONSE']._serialized_end=126
  _globals['_LOGGINGSERVICE']._serialized_start=128
  _globals['_LOGGINGSERVICE']._serialized_end=203
# @@protoc_insertion_point(module_scope)
