# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: goods_store.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'goods_store.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11goods_store.proto\x12\ngoodsstore\"A\n\x11UpdateUserRequest\x12\x0b\n\x03sid\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"\"\n\x0fWelcomeResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"-\n\rLoginResponse\x12\r\n\x05token\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"D\n\x13ProductListResponse\x12-\n\x08products\x18\x01 \x03(\x0b\x32\x1b.goodsstore.ProductResponse\"\x80\x01\n\x0fProductResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x04 \x01(\t\x12\r\n\x05price\x18\x05 \x01(\x02\x12\x0e\n\x06slogan\x18\x06 \x01(\t\x12\r\n\x05stock\x18\x07 \x01(\x05\"\x17\n\tProductId\x12\n\n\x02id\x18\x01 \x01(\x05\"S\n\x11\x43reateUserRequest\x12\x0b\n\x03sid\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x10\n\x08password\x18\x04 \x01(\t\"8\n\x08UserInfo\x12\x0b\n\x03sid\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"\x07\n\x05\x45mpty2\x93\x03\n\tDBService\x12\x39\n\x07Welcome\x12\x11.goodsstore.Empty\x1a\x1b.goodsstore.WelcomeResponse\x12\x41\n\x0bGetProducts\x12\x11.goodsstore.Empty\x1a\x1f.goodsstore.ProductListResponse\x12\x44\n\x0eGetProductById\x12\x15.goodsstore.ProductId\x1a\x1b.goodsstore.ProductResponse\x12\x41\n\nCreateUser\x12\x1d.goodsstore.CreateUserRequest\x1a\x14.goodsstore.UserInfo\x12<\n\x05Login\x12\x18.goodsstore.LoginRequest\x1a\x19.goodsstore.LoginResponse\x12\x41\n\nUpdateUser\x12\x1d.goodsstore.UpdateUserRequest\x1a\x14.goodsstore.UserInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'goods_store_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UPDATEUSERREQUEST']._serialized_start=33
  _globals['_UPDATEUSERREQUEST']._serialized_end=98
  _globals['_WELCOMERESPONSE']._serialized_start=100
  _globals['_WELCOMERESPONSE']._serialized_end=134
  _globals['_LOGINREQUEST']._serialized_start=136
  _globals['_LOGINREQUEST']._serialized_end=186
  _globals['_LOGINRESPONSE']._serialized_start=188
  _globals['_LOGINRESPONSE']._serialized_end=233
  _globals['_PRODUCTLISTRESPONSE']._serialized_start=235
  _globals['_PRODUCTLISTRESPONSE']._serialized_end=303
  _globals['_PRODUCTRESPONSE']._serialized_start=306
  _globals['_PRODUCTRESPONSE']._serialized_end=434
  _globals['_PRODUCTID']._serialized_start=436
  _globals['_PRODUCTID']._serialized_end=459
  _globals['_CREATEUSERREQUEST']._serialized_start=461
  _globals['_CREATEUSERREQUEST']._serialized_end=544
  _globals['_USERINFO']._serialized_start=546
  _globals['_USERINFO']._serialized_end=602
  _globals['_EMPTY']._serialized_start=604
  _globals['_EMPTY']._serialized_end=611
  _globals['_DBSERVICE']._serialized_start=614
  _globals['_DBSERVICE']._serialized_end=1017
# @@protoc_insertion_point(module_scope)
